---
- name: restart graylog-sidecar
  service:
    name:  graylog-sidecar
    enabled: true
    state: restarted

- name: restart filebeat
  service:
    name:  filebeat
    enabled: true
    state: restarted

- name: restart journalbeat
  service:
    name:  journalbeat
    enabled: true
    state: restarted
